
# Start from a Node.js 10 (LTS) image
FROM node:10

# Specify the directory inside the image in which all commands will run
WORKDIR /usr/src/app

# Copy package files and install dependencies
# COPY package*.json ./
COPY package*.json /usr/src/app/
# RUN npm install

# Copy all of the app files into the image
COPY . /usr/src/app/

# The default command to run when starting the container
# CMD [ "npm", "start" ]
CMD ["sh", "-c", "npm install express && npm start"]


